fix: disabled back button for Map Fragment in tablet view
fossasia/open-event-droidgen pull request #1723
Opened 2017-06-17 19:40 UTC by arp95

Fixes #1720 

Changes: 
Disabled back button for Map Fragment for tablet view of the app.

Screenshots for the change: 
![19264107_10211597374164410_1936271897_o](https://user-images.githubusercontent.com/8268392/27255755-e8be7a5c-53c2-11e7-9059-c1cf4369e532.jpg)

2017-06-17 19:40 UTC, arp95 commented
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

2017-06-18 05:00 UTC, iamareebjamal requested changes

2017-06-18 05:00 UTC, iamareebjamal commented on android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java
> +    private SharedPreferences sharedPreferences;
Don't use sharedpreference please. This should not be persisted

2017-06-18 05:13 UTC, arp95 commented on android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java
> +    private SharedPreferences sharedPreferences;
sure. looking for another way.

2017-06-18 05:20 UTC, arp95 commented on android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java
> +    private SharedPreferences sharedPreferences;
@iamareebjamal 
i am using the Utils class then and creating getters and setters to get the value? is it fine?

2017-06-18 06:41 UTC, iamareebjamal commented on android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java
> +    private SharedPreferences sharedPreferences;
Sure

2017-06-18 06:44 UTC, iamareebjamal approved these changes

2017-06-18 06:50 UTC, Shailesh351 approved these changes

2017-06-18 06:52 UTC, shreyasnbhat approved these changes
Looks Good

2017-06-18 09:15 UTC, iamareebjamal commented
Is there some bug in Travis or what

2017-06-18 09:16 UTC, iamareebjamal commented
Not even getting triggered on close and reopen

2017-06-18 09:17 UTC, the-dagger commented
@iamareebjamal Travis ran and the check passed successfully already.

2017-06-18 09:18 UTC, merged