feat : Make models jackson compatible for JSONAPI implementation
fossasia/open-event-droidgen pull request #1731
Opened 2017-06-22 12:44 UTC by Shailesh351

Fixes #1729  

Changes: 
- Transfer from Gson to Jackson

Here Dummy Observable class is needed.  Ref : https://realm.io/docs/java/latest/#jackson-databind

2017-06-22 12:45 UTC, Shailesh351 commented
@arp95 @iamareebjamal @shreyasnbhat Please review

2017-06-22 17:44 UTC, iamareebjamal requested changes
Some doubts. 

Did you add any field except getters and setters?

2017-06-22 17:44 UTC, iamareebjamal commented on android/app/build.gradle
> +        multiDexEnabled true
Is the build surpassing 65k methods?

2017-06-22 17:44 UTC, iamareebjamal commented on android/app/src/main/java/rx/Observable.java
> +    // RxJava is not a project dependency.
But RxJava is project dependency

2017-06-23 05:35 UTC, Shailesh351 commented on android/app/build.gradle
> +        multiDexEnabled true
Yes, it is because of jackson jar file is large and have more methods

2017-06-23 05:37 UTC, Shailesh351 commented
@iamareebjamal I have not added new fields. I have planned to add new fields and change Json property values when we switch to JSONAPI

2017-06-23 05:43 UTC, Shailesh351 commented on android/app/src/main/java/rx/Observable.java
> +    // RxJava is not a project dependency.
Yes it is but  For realm we have not used Observable. 
https://realm.io/docs/java/latest/#rxjava

2017-06-23 05:58 UTC, iamareebjamal approved these changes

2017-06-23 06:01 UTC, rohanagarwal94 approved these changes

2017-06-23 06:02 UTC, arp95 approved these changes

2017-06-23 06:04 UTC, merged

2017-06-23 06:05 UTC, shreyasnbhat commented
@Shailesh351 Sorry for the delay. Looking at this now.