fix: replaced field names with getter and setter annotations
fossasia/open-event-droidgen pull request #1742
Opened 2017-06-27 17:05 UTC by arp95

Fixes #1740 

Changes: 
replaced field names with the setter and getter annotations. will remove the old model ones, once the new api is up.

Screenshots for the change: 
-

@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

2017-06-27 18:21 UTC, iamareebjamal requested changes

2017-06-27 18:21 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/data/Event.java
> +    @JsonGetter("event_url")
No need to annotate getters, prefer JsonProperty there. Getter annotation creates unnecessary boilerplate. Only annotate setters when there are more than one attribute name for same property. JsonProperty should be preferred over JsonSet/Getter. But we have to delegate to setter when there are more than one attribute name, but there is no need of getter annotation as we don't serialize the POJOs, only deserialize

2017-06-27 18:33 UTC, arp95 commented on android/app/src/main/java/org/fossasia/openevent/data/Event.java
> +    @JsonGetter("event_url")
but if the atttribute has both a setter and a getter than should i make the json property the old one which will be used for the getter and update the setter with multiple field names?

2017-06-27 18:45 UTC, arp95 commented
@iamareebjamal 
made changes.

2017-06-27 18:45 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/data/Event.java
> +    @JsonGetter("event_url")
If there is a conflict in property name, then remove JsonProperty and create 2 setters with names from both properties

2017-06-27 18:46 UTC, iamareebjamal approved these changes

2017-06-27 18:46 UTC, iamareebjamal commented
There are more changes to be I guess @arp95 ?

2017-06-27 18:48 UTC, arp95 commented
@iamareebjamal 
i went through twice. but didnt find any setter method having conflicting attribute names. are there according to you?

2017-06-27 19:07 UTC, iamareebjamal commented
I mean there are much more additions to do make it compatible with new API

2017-06-27 19:09 UTC, arp95 commented
you mean the new attributes? plus i havent changed the attributes with getters for now. will cahnge them when the new api is set up.

2017-06-27 19:22 UTC, iamareebjamal commented
Please do those changes as well as it won't concern the old API and only make things easier when the new API is deployed

Your doc has listed some changes pertaining to attribute name in sessions, sponsors, etc. Do add setters for ambiguous attributes

https://docs.google.com/document/d/1caaCeOOTIxQn2HR1Uj9r-cHXQH5hSYzzzCJpt3rkl38/edit

2017-06-27 19:24 UTC, arp95 commented
so i have to these two things right?

add new attributes with jsonproperty and 
add setters for all conflicted attributes.

right?

2017-06-27 19:26 UTC, iamareebjamal commented
Just the second part in this PR. First part will require migrations too

2017-06-27 19:26 UTC, iamareebjamal requested changes
Add changes for conflicting attribute names

2017-06-27 20:21 UTC, arp95 commented
made changes. please see now.

2017-06-28 16:52 UTC, iamareebjamal commented
@arp95 The build is failing, please take a look

2017-06-28 17:31 UTC, arp95 commented
@iamareebjamal 
please review now.

2017-06-28 18:23 UTC, iamareebjamal submitted a review, later dismissed

2017-06-29 02:42 UTC, arp95 commented
@Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

2017-06-29 05:31 UTC, Shailesh351 requested changes

2017-06-29 05:31 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/data/Sponsor.java
> +    @JsonSetter("session_type")
It should be `sponsor_type`

2017-06-29 05:31 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/data/Sponsor.java
> +    @JsonSetter("session-type")
here also

2017-06-29 05:42 UTC, arp95 commented
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review now.

2017-06-29 05:47 UTC, Shailesh351 approved these changes

2017-06-29 08:06 UTC, arp95 commented
@mariobehling @the-dagger 
please review now.

2017-06-29 09:16 UTC, iamareebjamal approved these changes

2017-06-29 09:57 UTC, merged