fix : Improve map fragment
fossasia/open-event-droidgen pull request #1749
Opened 2017-06-29 13:29 UTC by Shailesh351

Fixes #1743 

Changes: 
- Fixed padding before autocomplete search view
- Changed autocomplete textview to SearchView.SearchAutoComplete to make UI consistent
- Showed marker info on clicking on suggestion
- Added null check for event and location

Screenshots for the change: 

![videotogif_2017 06 29_18 48 32](https://user-images.githubusercontent.com/18264684/27689797-ff4e9b4c-5cfc-11e7-8408-bada856e556b.gif)

2017-06-29 13:31 UTC, Shailesh351 commented
@arp95 @shreyasnbhat @iamareebjamal @rohanagarwal94 Please review

2017-06-29 13:41 UTC, Shailesh351 commented
Which one will be better  ?

![videotogif_2017 06 29_19 08 35](https://user-images.githubusercontent.com/18264684/27690307-9ad4d85a-5cfe-11e7-8b6e-7d7346173ed3.gif)

2017-06-30 02:51 UTC, shreyasnbhat commented
@Shailesh351 I think that the 2nd one would be better

2017-06-30 02:56 UTC, arp95 commented
i think the same. 2nd will be better.

2017-07-01 16:35 UTC, Shailesh351 commented
Do not merge this PR. Some work is remaining. Working on it

2017-07-01 19:39 UTC, Shailesh351 commented
Guys now clicking map icon from sesssion detail activity and location activity directly focus on corresponding location and shows marker info of that location. :tada: 

Ready to merge.
@iamareebjamal @arp95 @shreyasnbhat @rohanagarwal94 Please review now.

2017-07-01 19:57 UTC, Shailesh351 commented
![videotogif_2017 07 02_01 25 20](https://user-images.githubusercontent.com/18264684/27765038-9f44b6ee-5ec5-11e7-8a12-6e5486eebf41.gif)

2017-07-01 21:45 UTC, iamareebjamal requested changes

2017-07-01 21:45 UTC, iamareebjamal commented on android/app/src/fdroid/java/org/fossasia/openevent/fragments/OSMapFragment.java
>  //    private void launchDirections() {
Can you remove the comments too? Thanks

2017-07-02 09:10 UTC, iamareebjamal approved these changes

2017-07-02 19:24 UTC, merged