Implement caching in the livefeed
fossasia/open-event-droidgen pull request #1750
Opened 2017-06-29 16:14 UTC by rohanagarwal94

Fixes #1735

This will implement caching in the live feed and solve app crash in the global search.

2017-06-29 16:16 UTC, rohanagarwal94 commented
@iamareebjamal @arp95 @Shailesh351 @shreyasnbhat please review.

2017-06-29 16:38 UTC, iamareebjamal requested changes

2017-06-29 16:38 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +                    .client(okHttpClient);
Please pre-build the common functionalities statically. This code block is duplicated

2017-06-29 16:57 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +                    .client(okHttpClient);
the okHttpClient paramter is not same. I have provided the cache and added the interceptor for the the facebook okhttpclient.

2017-06-29 17:01 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +                    .client(okHttpClient);
I know. Still, the retrofit bit except client is same. Similar to what it was before.

2017-06-29 17:28 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +                    .client(okHttpClient);
okay, doing it.

2017-06-30 04:35 UTC, rohanagarwal94 commented
@iamareebjamal updated.

2017-06-30 05:57 UTC, iamareebjamal requested changes

2017-06-30 05:57 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
This will block the main thread for seconds if there's a slow connection

2017-06-30 05:57 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +        catch (Exception e) {
Move cache to previous line

2017-06-30 06:18 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
So any suggestions for this?

2017-06-30 07:49 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
Why does this need to be dynamic?

2017-07-01 08:34 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
If the user is offline, he will not get the cache response automatically. The okhttp will not be able to reach the API endpoint.The request header should only be modified if the user is offline. The stale results will only be offered if the new feed cannot be fetched.

2017-07-01 16:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
OK

2017-07-01 16:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/APIClient.java
> +            if (!NetworkUtils.haveNetworkConnection(OpenEventApp.getAppContext())) {
Just add the cache syntax fix

2017-07-01 16:57 UTC, rohanagarwal94 commented
@iamareebjamal please review now.

2017-07-01 17:03 UTC, iamareebjamal requested changes

2017-07-01 17:03 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> -        OpenEventApp.getEventBus().unregister(this);
Why is this removed? This will cause a memory leak

2017-07-01 17:27 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> -        OpenEventApp.getEventBus().unregister(this);
There is no event bus registered for the fetching of feed event the reason being that rxJava was used to subscribe to feed observable.

2017-07-01 17:28 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> -        OpenEventApp.getEventBus().unregister(this);
OK

2017-07-01 17:40 UTC, rohanagarwal94 commented
@arp95 @iamareebjamal @Shailesh351 @shreyasnbhat please review.

2017-07-01 19:03 UTC, iamareebjamal approved these changes

2017-07-01 19:35 UTC, arp95 approved these changes
LGTM.

2017-07-01 20:07 UTC, Shailesh351 approved these changes
Looks good. 

One suggestion it is not caching images so when offline it is showing big camera icons. Will it be better to  show image if it is loaded otherwise not visible ?

2017-07-02 06:40 UTC, rohanagarwal94 commented
@shailesh351 I initially stored images in the picasso cache which you implemented. But @iamareebjamal pointed out that since the feed is bound to have new content frequently, the cache would fill up quickly.

2017-07-02 09:30 UTC, iamareebjamal commented
@rohanagarwal94 You can set appropriate placeholder image so that it does not look weird while loading, however that is another issue

2017-07-02 16:57 UTC, rohanagarwal94 commented
@iamareebjamal the placeholder is already set to a camera icon.

2017-07-02 17:13 UTC, iamareebjamal commented
The problem as @Shailesh351 said was that it was not appropriate in this setting. As it appeared enlarged. See if you can an appropriate placeholder

2017-07-02 17:31 UTC, rohanagarwal94 commented
@iamareebjamal let me create another issue for it. Discussing that here is futile IMO.
@mariobehling @the-dagger please review and merge.

2017-07-02 19:25 UTC, merged