fix : Remove menu icons from map fragment
fossasia/open-event-droidgen pull request #1754
Opened 2017-06-30 14:24 UTC by Shailesh351

Fixes #1752 

Changes: 
- Removed menu icons from session details activity and locat
tion activity
- Changed toolbar title from session name to location name when showing map fragment

Screenshots for the change: 

![videotogif_2017 06 30_19 51 16](https://user-images.githubusercontent.com/18264684/27739911-d307611e-5dcd-11e7-8b8a-51a8cc2adf0a.gif)

2017-06-30 14:25 UTC, Shailesh351 commented
@iamareebjamal @arp95 @rohanagarwal94 @shreyasnbhat Please review

2017-06-30 14:28 UTC, iamareebjamal requested changes

2017-06-30 14:28 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
> +            sessionRecyclerView.setVisibility(View.VISIBLE);
Both conditions are `VISIBLE`

2017-06-30 14:29 UTC, arp95 commented on android/app/src/main/res/values/styles.xml
> +        <item name="android:textSize">22sp</item>
please use the value from dimens.xml

2017-06-30 14:45 UTC, arp95 approved these changes
LGTM.

2017-06-30 14:47 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
> +            sessionRecyclerView.setVisibility(View.VISIBLE);
Yes, but one is for noSessionsView and second is for sessionRecyclerView. 
On clicking we are setting visibility of both to GONE. So on pressing back button one of them should be visible

2017-06-30 15:43 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java
> +            sessionRecyclerView.setVisibility(View.VISIBLE);
OK

2017-06-30 15:45 UTC, iamareebjamal submitted a review, later dismissed

2017-06-30 16:24 UTC, shreyasnbhat approved these changes

2017-07-01 10:29 UTC, rohanagarwal94 commented
@shailesh351 please squash commits.

2017-07-01 16:27 UTC, merged