fix: removed all the attributes of old models
fossasia/open-event-droidgen pull request #1772
Opened 2017-07-04 17:51 UTC by arp95

Fixes #1768 

Changes: 
removed all attributes of old models and made the models compatible to the new api except the event and speaker model.

Screenshots for the change: 
-

@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

2017-07-04 18:06 UTC, iamareebjamal requested changes

2017-07-04 18:06 UTC, iamareebjamal commented on android/app/src/main/assets/microlocations
> +{
This is incorrect. The API and JSON have a different format. We want to use this format for JSON https://github.com/fossasia/open-event/wiki/%5BNextgen%5D-Open-Event-Universal-Format-Specification

2017-07-04 18:06 UTC, iamareebjamal commented on android/app/src/main/assets/microlocations
> +{
Not the API format

2017-07-04 18:23 UTC, arp95 commented
@iamareebjamal updated. please see now.

2017-07-04 18:43 UTC, Shailesh351 commented on android/app/src/main/assets/microlocations
>  [
Don't remove sample data. Please change attributes names using script you wrote. Sample should contain more data.

2017-07-04 18:44 UTC, arp95 commented on android/app/src/main/assets/microlocations
>  [
yes you are right. doing it

2017-07-04 19:29 UTC, arp95 commented
@iamareebjamal @Shailesh351 
please review now.

2017-07-04 19:39 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/data/Session.java
> +    @JsonProperty("videos-url")
`video-url` it is changed :sweat_smile: 
Please look at other attributes also

2017-07-05 02:48 UTC, arp95 commented
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review now.

2017-07-05 04:46 UTC, Shailesh351 commented
@arp95 event sample file also needs to be changed. I think you missed it.

2017-07-05 04:52 UTC, arp95 commented
@Shailesh351 
actually the event model has a separate pr so i have left the event and speaker model for now as stated above.
please review the other and approve.

2017-07-05 06:43 UTC, Shailesh351 approved these changes
LGTM

2017-07-05 07:49 UTC, iamareebjamal submitted a review, later dismissed

2017-07-05 11:31 UTC, rohanagarwal94 approved these changes

2017-07-05 11:59 UTC, Shailesh351 requested changes
@arp95 In sessions file, not all attributes are changed. Please have a look. Change it accordingly.

2017-07-05 14:20 UTC, arp95 commented
can you please mention the ones not there. because according to me audio and video attribute changed.

2017-07-05 14:23 UTC, Shailesh351 commented
@arp95 See https://github.com/arp95/open-event-android/blob/efbca32ab79e22f003efd77897062b3e38eb9914/android/app/src/main/assets/sessions#L55

2017-07-05 15:10 UTC, arp95 commented
guys please review this and approve.
@Shailesh351 @iamareebjamal

2017-07-05 15:14 UTC, Shailesh351 approved these changes

2017-07-05 15:24 UTC, arp95 commented
@mariobehling @the-dagger 
please review and merge.

2017-07-05 16:31 UTC, iamareebjamal approved these changes

2017-07-05 16:40 UTC, merged