fix: Stop downloading data on network change
fossasia/open-event-droidgen pull request #1793
Opened 2017-07-09 07:17 UTC by rohanagarwal94

Fixes #1765 

Changes: 

- [x] Stops listening to network changes.
- [x] Recreation of progress bar object to prevent stacking of strings.
- [x] Create a new complete handler object every time to prevent doubling up of subscribing events.

@iamareebjamal @arp95 @Shailesh351 @shreyasnbhat @mahikaw please review.

2017-07-09 14:02 UTC, iamareebjamal requested changes

2017-07-09 14:02 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java
> +                                        OpenEventApp.postEventOnUIThread(new DataDownloadEvent());
Um, this isn't correct, we shouldn't be posting a download event

2017-07-09 14:02 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java
> +                                        Toast.makeText(reference.get(), R.string.waiting_for_network, Toast.LENGTH_LONG).show();
Same here

2017-07-09 17:28 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java
> +                                        OpenEventApp.postEventOnUIThread(new DataDownloadEvent());
oh sorry, missed it. Updating it.

2017-07-09 18:07 UTC, rohanagarwal94 commented
@iamareebjamal updated.

2017-07-09 19:03 UTC, iamareebjamal commented
As there are no tests, please manually check if it is working in all cases

2017-07-09 19:46 UTC, rohanagarwal94 commented
@iamareebjamal yeah did that. Swipe refreshes, Initial app start, app start from pause.

2017-07-09 19:56 UTC, iamareebjamal approved these changes

2017-07-10 08:12 UTC, rohanagarwal94 commented
@mariobehling @the-dagger please review.

2017-07-10 17:40 UTC, rohanagarwal94 commented
@Shailesh351 @arp95 @shreyasnbhat @mahikaw please review.

2017-07-10 19:36 UTC, arp95 approved these changes
LGTM.

2017-07-10 22:25 UTC, merged