Enabled APK mailing on app generator
fossasia/open-event-droidgen pull request #1818
Opened 2017-07-15 11:03 UTC by mahikaw

Fixes #1601 

Changes: Enabled app generator to mail APK via:

- Sendgrid, or
- SMTP 

-----

@niranjan94 @the-dagger @iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 @arp95 Please review.

2017-07-15 17:35 UTC, niranjan94 requested changes
@mahikaw

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
>          :param via_api:
This function is just for choosing which method to use. SMTP related config to be done in the smtp send method. Sendgrid config to be done sendgrid method.

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +                Notification.send_email_task.delay(payload, headers)
No `delay` here

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +        message.plain = message
Why are you assigning `message` to a property of `message` ? Should be the message from the payload.

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    EMAIL_SERVICE=os.environ.get('SERVICE_MAIL')
Space around `=` for all of this.

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    EMAIL_SERVICE=os.environ.get('SERVICE_MAIL')
Call env variable also as `EMAIL_SERVICE` and keep default as sendgrid.

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    SMTP_ENCRYPTION=os.environ.get('ENCRYPTION_MAIL')
Call env variable also as `SMTP_ENCRYPTION`

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    HOST=os.environ.get('HOST_MAIL')
Call both variable and env variable as `SMTP_HOST`

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    USERNAME=os.environ.get('USERNAME_MAIL')
Call both variable and env variable as `SMTP_USERNAME`

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    PASSWORD=os.environ.get('PASSWORD_MAIL')
Call both variable and env variable as `SMTP_PASSWORD`

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    PORT=os.environ.get('PORT_MAIL')
Call both variable and env variable as `SMTP_PORT`

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    TESTING=os.environ.get('TESTING_MAIL')
What is this ?

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    SENDGRID_KEY=os.environ.get('SENDGRID_KEY_MAIL')
Call both variable and env variable as `SENDGRID_KEY `

2017-07-15 17:35 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +                    "Authorization": ("Bearer " + key)
Why the brackets ?

2017-07-15 18:46 UTC, mahikaw commented
Updated @niranjan94 Please review.

2017-07-15 18:47 UTC, iamareebjamal requested changes

2017-07-15 18:47 UTC, iamareebjamal commented on apk-generator/v2/config.py
> +    EMAIL_SERVICE = os.environ.get('EMAIL_SERVICE','sendgrid')
Add space after comma

2017-07-15 18:53 UTC, niranjan94 requested changes
@mahikaw

2017-07-15 18:53 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +            'from': current_app.config['SMTP_USERNAME'],
The smtp username may not always be an email address. And why would there be an smtp username if the the user wants to use sendgrid. ? 

So, have a separate variable called as `FROM_EMAIL`

2017-07-15 18:53 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +            print 'Sendgrid key not defined'
Use the logger to log stuff

2017-07-15 18:53 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +    def send_email_task(payload):
call this `send_email_via_sendgrid`

2017-07-15 18:53 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +        message.plain = payload['message']
The `message` is a rich text string. (Has html tags). So, have both `message.plain` (with html tags stripped) and `message.rich`

2017-07-15 18:53 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
>  # TODO Notifications have to be implemented. API/SMTP/Sendgrid depending on a configuration
Update this comment

2017-07-15 19:13 UTC, mahikaw commented
@niranjan94 @iamareebjamal , updated it.

2017-07-15 19:23 UTC, niranjan94 requested changes

2017-07-15 19:23 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> -# TODO Notifications have to be implemented. API/SMTP/Sendgrid depending on a configuration
I meant ... API implementation is still remaining, so keep the TODO for that

2017-07-15 19:23 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +        if email_service == 'smtp':
Send via smtp or sendgrid, only if `via_api` is `False`

2017-07-15 19:23 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
>          message.rich = payload['html']
There is no param called `html`. Its called as `message`. Put that in rich and use strip tags function on it and use that for plain.

2017-07-15 19:24 UTC, niranjan94 requested changes

2017-07-15 19:24 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    FROM_EMAIL =os.environ.get('FROM_EMAIL')
Space after `=` please

2017-07-15 19:24 UTC, mahikaw commented on apk-generator/v2/app/utils/notification.py
>          message.rich = payload['html']
um yes. Sorry of not taking care.

2017-07-15 19:24 UTC, mahikaw commented on apk-generator/v2/config.py
> +    FROM_EMAIL =os.environ.get('FROM_EMAIL')
Updating 👍

2017-07-15 19:34 UTC, mahikaw commented
Updated @niranjan94

2017-07-16 15:04 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> -# TODO Notifications have to be implemented. API/SMTP/Sendgrid depending on a configuration
Isn't resolved yet @mahikaw

2017-07-18 04:45 UTC, mahikaw commented
@iamareebjamal @niranjan94 Please approve if there aren't any further changes required.

2017-07-18 05:05 UTC, niranjan94 requested changes

2017-07-18 05:05 UTC, niranjan94 commented on apk-generator/v2/config.py
> +    EMAIL_SERVICE = os.environ.get('EMAIL_SERVICE', 'sendgrid')
Keep default as `none`. If none, email service should be disabled.

2017-07-18 05:05 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +        message.attach(payload['attachment'], data=None, maintype=None, subtype=None, inline=False)
Are all the additional `None` arguments required?

2017-07-18 05:05 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +    def send_mail_via_smtp_(payload):
Why the underscore at the end?

2017-07-18 05:05 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +    def send_email_via_sendgrid_(payload):
Why the underscore at the end.?

2017-07-18 18:11 UTC, mahikaw commented on apk-generator/v2/config.py
> +    EMAIL_SERVICE = os.environ.get('EMAIL_SERVICE', 'sendgrid')
In one of the earlier reviews, you suggested to set it to 'send grid'. I'll make it none then and add a condition to check that as well?

2017-07-18 18:13 UTC, mahikaw commented on apk-generator/v2/app/utils/notification.py
> +        message.attach(payload['attachment'], data=None, maintype=None, subtype=None, inline=False)
I had done this after seeing the Marrow mailer [documentation](https://github.com/marrow/mailer). I think they are required. The maintop can be remove though, I'll do that.

2017-07-18 18:14 UTC, niranjan94 commented
Yes... I had suggested that. But.. I think the generator itself should work
without the need for an email server. (no emails. Wait and download).

So, have a none option. And keep it default. Also update the Readme file
with details about email.

On Tue, Jul 18, 2017, 11:41 PM Mahika Wason <notifications@github.com>
wrote:

> *@mahikaw* commented on this pull request.
> ------------------------------
>
> In apk-generator/v2/config.py
> <https://github.com/fossasia/open-event-android/pull/1818#discussion_r128053183>
> :
>
> > @@ -22,7 +22,14 @@ class Config:
>      CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
>      CELERY_RESULT_BACKEND = CELERY_BROKER_URL
>      SECRET_KEY = os.environ.get('SECRET_KEY', 'JQgeEYk9b4VjxhJP')
> -
> +    EMAIL_SERVICE = os.environ.get('EMAIL_SERVICE', 'sendgrid')
>
> In one of the earlier reviews, you suggested to set it to 'send grid'.
> I'll make it none then and add a condition to check that as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/open-event-android/pull/1818#discussion_r128053183>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACSwFBKsLjOw0aedE6zfKnfiP5cM76Ecks5sPPVZgaJpZM4OY_JO>
> .
>

2017-07-19 07:55 UTC, mahikaw commented
@niranjan94 Updated as per suggestions. Please review the changes.

2017-07-19 08:56 UTC, niranjan94 requested changes

2017-07-19 08:56 UTC, niranjan94 commented on apk-generator/v2/app/utils/notification.py
> +        message.attach(payload['attachment'], data=None, maintype=None, subtype=None, inline=False)
@mahikaw see here https://github.com/marrow/mailer/blob/develop/marrow/mailer/message.py#L254 ... The other arguments are not needed. The defaults are `None` anyway. So remove them please. Once this is done, I think the PR can be merged. 

Good work :)

2017-07-19 09:00 UTC, mahikaw commented
Updated @niranjan94 👍

2017-07-19 09:10 UTC, niranjan94 approved these changes

2017-07-20 06:43 UTC, rohanagarwal94 approved these changes

2017-07-20 07:57 UTC, merged