feat:Added datewise organization of bookmarks in homescreen
fossasia/open-event-droidgen pull request #1823
Opened 2017-07-15 20:13 UTC by shreyasnbhat

Fixes #1810 

Changes

1. Modified GlobalSearchAdapter to use in the Homescreen.
2. GlobalSearchAdapter can be renamed as GenericAdapter.
3. Added date-wise splitting of bookmarks.

Screenshots for the change: 
![ac5d8cf5-dafe-4cd2-a49a-66f00d2c31fe](https://user-images.githubusercontent.com/19890557/28242396-f85e4d8c-69c7-11e7-9020-1f9771f1eb75.jpg)

2017-07-15 20:14 UTC, shreyasnbhat commented
@iamareebjamal @Shailesh351 @arp95 @rohanagarwal94 Please review.
I would need some help in what to use from DateUtils to convert this date string to the one with the day eg. Mon , 17 July , 2017

2017-07-15 21:50 UTC, iamareebjamal commented
@shreyasnbhat Create a new Date format string and its SimpleDateFormatter, add it in the switch case mapper, and use the getDateStringWithDefault with that String parameter

2017-07-16 09:54 UTC, shreyasnbhat commented
@iamareebjamal @arp95 @Shailesh351   What shall I do about the 2 headers? Shall I remove the Bookmark Header entirely? As there are 2 headers back to back for exmple. Bookmarks and then 17 Mar.

2017-07-16 09:57 UTC, Shailesh351 commented
@shreyasnbhat You can keep Bookmarks header and for dates header make it gray as we have in DayScheduleFragment.

2017-07-16 10:04 UTC, shreyasnbhat commented
@Shailesh we can add sticky headers later. It would have to be implemented in the entire home screen for a consistent UI. 
For that to work we would have to get all the event-info items as ViewHolders and would involve major refactoring of code.

2017-07-16 14:22 UTC, shreyasnbhat commented
@iamareebjamal @Shailesh351 @arp95 Updated.
Screeshot
![39a73269-57fc-46db-9b3d-f7bfc602e972](https://user-images.githubusercontent.com/19890557/28248275-c53a5836-6a5f-11e7-951e-f848c35367d7.jpg)

2017-07-17 17:59 UTC, shreyasnbhat commented
@Shailesh351 @iamareebjamal @arp95 Please review.

2017-07-18 03:43 UTC, Shailesh351 requested changes
Instead of adding bookmarks in Global search adapter.
Create new BookmarksAdapter and implement stickeadersRecycleView. Return bookmarked session date as header id.
Look at other adapters for reference. It will simply take 6-7 line of code to add sticky headers in recyclerview

2017-07-18 03:43 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    private GlobalSearchAdapter bookMarksListAdapter;
@shreyasnbhat Adding bookmarks in Global Search results is not a good idea. Bookmarks are specific to particular user and global search should give results from all over the app.

2017-07-18 03:54 UTC, shreyasnbhat commented
@Shailesh351 The global search adapter does give results from multiple sources. Bookmarks can very well be a source. I proposed that we rename Global search adapter to something like Generic Adapter as there would be un-necessary code duplication for no reason if I made another adapter called Bookmarks adapter. If I want to go ahead with adding sessions/bookmarked sessions in the global search this would be the best way to go. And for the addition of sticky headers I can do it but the question is that whether the UI will consistent with white background headers being sticky and the other red headers not being sticky. Additionally the red headers are all static in nature. Sticky headers just creates inconsistent UI here. What happens when we reach the end of the bookmarks? We would probably have a header with the text 19th Mar with no bookmarks below it which is wierd. 
In a gist I strongly feel that we shouldn't add sticky headers here. @iamareebjamal @arp95 please suggest.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-07-18 03:56 UTC, shreyasnbhat commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    private GlobalSearchAdapter bookMarksListAdapter;
Global Search is meant for the user only. GlobalSearchAdapter can be renamed into GenericAdapter

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-07-20 05:36 UTC, shreyasnbhat commented
@the-dagger @iamareebjamal @arp95 Please review and merge.

2017-07-22 19:39 UTC, iamareebjamal requested changes

2017-07-22 19:39 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java
> +                else{
else in previous line please

2017-07-22 19:39 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +
Remove extra line

2017-07-22 19:39 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    final ArrayList<String> dateList = new ArrayList<>();
private

2017-07-22 19:39 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    private List<Object> mSessions = new ArrayList<>();
Why object?

2017-07-22 19:45 UTC, shreyasnbhat commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    private List<Object> mSessions = new ArrayList<>();
Global Search Adapter is used and as we also have the Date Headers we need to use Object.

2017-07-22 19:48 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +    private List<Object> mSessions = new ArrayList<>();
OK

2017-07-22 20:05 UTC, shreyasnbhat commented
@iamareebjamal  Updated.

2017-07-23 08:32 UTC, shreyasnbhat commented
@iamareebjamal Please review.

2017-07-23 09:08 UTC, iamareebjamal requested changes
Just this one change more

2017-07-23 09:08 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +                            catch (ParseException e){
Catch in previous line

2017-07-23 09:56 UTC, iamareebjamal submitted a review, later dismissed

2017-07-23 14:22 UTC, shreyasnbhat commented
@arp95 @rohanagarwal94 @mahikaw Please review.

2017-07-23 14:27 UTC, rohanagarwal94 requested changes

2017-07-23 14:27 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java
> +                if(context instanceof SearchActivity){
Add space here before `{`

2017-07-23 14:39 UTC, shreyasnbhat commented
@rohanagarwal94 Updated.

2017-07-23 15:38 UTC, shreyasnbhat commented
@iamareebjamal @rohanagarwal94 @arp95 Updated guys. Please review. All minor changes done.

2017-07-26 10:44 UTC, iamareebjamal approved these changes

2017-07-26 11:22 UTC, shreyasnbhat commented
@rohanagarwal94 @arp95 Please review.

2017-07-27 06:15 UTC, rohanagarwal94 approved these changes

2017-07-27 17:34 UTC, merged