[WIP]feat : Add User Authentication
fossasia/open-event-droidgen pull request #1827
Opened 2017-07-17 17:13 UTC by Shailesh351

Fixes #363 

Changes:

- [x] Add login activity
- [ ] Add User, Login model and setup API service
- [ ] Add JWT Utils

2017-07-21 14:55 UTC, Shailesh351 commented
Sign Up Demo
![signup](https://user-images.githubusercontent.com/18264684/28468920-263d322a-6e52-11e7-9b36-453baf679c4b.gif)

Login Demo
![signin](https://user-images.githubusercontent.com/18264684/28468940-36e9809c-6e52-11e7-964b-9ff4c316deeb.gif)

@iamareebjamal @arp95 @mahikaw @rohanagarwal94 @shreyasnbhat Please test and review.
@mananwason @the-dagger Please review.

Almost all the work for user authentication is done. Log out is remaining. I'll add it soon.

2017-07-22 09:07 UTC, Shailesh351 commented
@niranjan94  Should we add option for isAuthEnabled in config.json ?

2017-07-22 09:10 UTC, niranjan94 commented
> Should we add option for isAuthEnabled in config.json ? According to it app will show auth feature.

@Shailesh351 sounds good. Add also, this needs to be given as an option in the generator. (But that can come in a separate PR)

2017-07-22 09:24 UTC, Shailesh351 commented
@iamareebjamal @arp95 @mahikaw @rohanagarwal94 @shreyasnbhat Please test and review :smile:

2017-07-22 10:42 UTC, iamareebjamal requested changes

2017-07-22 10:42 UTC, iamareebjamal commented on android/app/src/main/assets/config.json
> +  "Api_Link": "http://open-event-dev.herokuapp.com/api/v1/events/6/"
No such event exists and use https

2017-07-22 10:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/LoginActivity.java
> +        loginResponseObserver = new Observer<LoginResponse>() {
Why creating a new Observer? Subscribe and pass the appropriate components

2017-07-22 10:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/LoginActivity.java
> +    }
This isn't needed if no action is triggered here

2017-07-22 10:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SignUpActivity.java
> +        signUpResponseObserver = new Observer<User>() {
Same thing about observer

2017-07-22 10:42 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/UserProfileActivity.java
> +        Timber.d("Removes token & email and logged out successfully");
Removed

2017-07-22 11:08 UTC, Shailesh351 commented on android/app/src/main/assets/config.json
> +  "Api_Link": "http://open-event-dev.herokuapp.com/api/v1/events/6/"
I changed it to test it on development deployment. Actually i forgot to change it back. Will change it :+1:

2017-07-22 11:09 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/activities/LoginActivity.java
> +        loginResponseObserver = new Observer<LoginResponse>() {
You mean using doOnSubscribe(), doOnNext(), etc.. ?

2017-07-22 12:02 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/LoginActivity.java
> +        loginResponseObserver = new Observer<LoginResponse>() {
No. subscribe(data -> { // onNext }, throwable -> { // error }, () -> { // completed })

2017-07-22 12:47 UTC, Shailesh351 commented
@iamareebjamal Made changes please review now

2017-07-24 22:50 UTC, iamareebjamal requested changes
I think it'll be better if you continue this after JSONAPI PR is completed

2017-07-24 22:50 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/api/network/OpenEventAPI.java
> +    Observable<LoginResponse> login(@Body Login login);
This is not the correct endpoint. It should be `/auth/session` I guess

2017-07-24 22:50 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/data/auth/LoginResponse.java
> +@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
I think you are creating auth for older API. Please develop for JSONAPI

2017-07-27 03:49 UTC, Shailesh351 commented
@iamareebjamal @mahikaw @rohanagarwal94 @shreyasnbhat @arp95 Please review :smile:

2017-07-30 05:28 UTC, Shailesh351 commented
@iamareebjamal @rohanagarwal94 @shreyasnbhat @arp95 Guys please review :smile:

2017-07-30 08:33 UTC, iamareebjamal approved these changes

2017-07-30 09:00 UTC, rohanagarwal94 approved these changes

2017-07-30 14:08 UTC, merged