Sessions in search
fossasia/open-event-droidgen pull request #1840
Opened 2017-07-22 17:13 UTC by shreyasnbhat

Fixes #1826 

TO BE MERGED ONLY AFTER #1823 

## Screenshot
![9ef348ea-98e8-4555-a918-dab2a76c3e4d](https://user-images.githubusercontent.com/19890557/28493135-9b9552e6-6f2e-11e7-8b6c-f49c5b8af876.jpg)

2017-07-27 19:26 UTC, shreyasnbhat commented
@iamareebjamal @Shailesh351 @arp95 @rohanagarwal94 Please review.

2017-07-30 04:36 UTC, shreyasnbhat commented
@Shailesh351 @rohanagarwal94 Please review.

2017-07-30 04:42 UTC, iamareebjamal submitted a review, later dismissed

2017-07-30 04:51 UTC, rohanagarwal94 requested changes

2017-07-30 04:51 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java
>              if(microlocations.size()>0) {
The formatting is not followed. There needs to be space after `if`. Its best to press `Ctrl + Alt + LShift + L` to format the entire file on the go.

2017-07-30 04:59 UTC, shreyasnbhat commented
@rohanagarwal94 @iamareebjamal @Shailesh351 Please check now. Updated.

2017-07-30 05:08 UTC, rohanagarwal94 requested changes

2017-07-30 05:08 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java
>          } else if(filteredResultList.get(position) instanceof Session){
This file is not formatted. Please do it here also.

2017-07-30 05:08 UTC, rohanagarwal94 commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
>                          if(!headerCheck){
Even here.

2017-07-30 05:19 UTC, shreyasnbhat commented
@rohanagarwal94 @iamareebjamal @Shailesh351 Check now. Updated.

2017-07-30 05:23 UTC, Shailesh351 approved these changes
Looks good to me

2017-07-30 05:31 UTC, rohanagarwal94 approved these changes

2017-07-30 15:37 UTC, shreyasnbhat commented
@iamareebjamal Please review.

2017-07-31 07:11 UTC, mariobehling commented
Thank you.

2017-07-31 07:11 UTC, merged