[WIP] fix : Show download dialog on emulator
fossasia/open-event-droidgen pull request #1869
Opened 2017-08-11 18:35 UTC by Shailesh351

Fixes #1868 

Changes:

- Remove active internet connection check
- Remove ShowNotificationSnackbar method which is **redundant** because snackbar is also shown using event bus(DownloadEvent)
- Update sample api-link

2017-08-12 03:56 UTC, iamareebjamal requested changes

2017-08-12 03:56 UTC, iamareebjamal commented on android/app/src/main/assets/config.json
> +  "api-link": "https://api.eventyay.com/v1/events/20",
It's better to depend on develop server instead

2017-08-12 06:42 UTC, Shailesh351 commented
@iamareebjamal @mejariamol Please review

2017-08-12 09:49 UTC, mejariamol requested changes

2017-08-12 09:49 UTC, mejariamol commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +                    }, throwable -> Timber.d("Facebook page id download failed: " + throwable.toString()));
please check if the indentation is correct.

2017-08-12 09:49 UTC, mejariamol commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +    public void showErrorSnackbar(String errorType, String errorDesc) {
may just pass the error as a parameter.

2017-08-12 09:49 UTC, mejariamol commented on android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
> +        if (swipeRefreshLayout != null && swipeRefreshLayout.isRefreshing())
this part seems repeating at more than one places. Have a utility method which takes in the refresh layout and does the action.

2017-08-12 09:49 UTC, mejariamol commented on android/app/src/main/java/org/fossasia/openevent/utils/Notification.java
>          android.net.NetworkInfo isWifi = connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI);
change the field name `isWifi` to something else, it seems a boolean by name. may be just `Wifi` is enough.

2017-08-13 10:58 UTC, Shailesh351 commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +    public void showErrorSnackbar(String errorType, String errorDesc) {
Snackbar will not able to show whole error message in one line. That's why i'm using it.

2017-08-13 10:58 UTC, Shailesh351 commented
@mejariamol @iamareebjamal Updated please review.

2017-08-13 11:11 UTC, iamareebjamal submitted a review, later dismissed

2017-08-13 11:43 UTC, mejariamol approved these changes

2017-08-13 11:45 UTC, mejariamol commented
@Shailesh351 Please squeeze your commits into one. It is a good practice to have one commit per PR.

2017-08-15 07:47 UTC, iamareebjamal approved these changes

2017-08-15 07:47 UTC, merged