fix : Update Event dated on timezone preference change
fossasia/open-event-droidgen pull request #1893
Opened 2017-08-23 13:04 UTC by Shailesh351

Fixes #1892 

Changes:
- Update event dates in the database on changing timezone preference in settings

2017-08-23 13:16 UTC, Shailesh351 commented
@iamareebjamal @heysadboy  Please review

2017-08-24 08:59 UTC, heysadboy commented on android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java
>              getSupportActionBar().setElevation(Utils.dpToPx(4));
Why setting the elevation dynamically? I think we could use AppBarLayout. It's fine anyways.  

-- android.support.design.widget.AppBarLayout

Then toolbar inside it.

2017-08-24 15:27 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java
>              getSupportActionBar().setElevation(Utils.dpToPx(4));
@heysadboy This change is not part of this PR

2017-08-24 15:31 UTC, iamareebjamal requested changes

2017-08-24 15:31 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java
> +    }
This whole block is synchronous, even the fromCallable method. So, there is no need for the fromCallable method.

2017-08-25 10:11 UTC, iamareebjamal approved these changes

2017-08-25 11:27 UTC, merged