fix: UI bug fix
fossasia/open-event-droidgen pull request #1927
Opened 2017-09-23 21:05 UTC by manki11

Fixes #1926 

margin-right was increased so the textview no longer overlaps the share button.

Screenshots for the change: 
Before:
![whatsapp image 2017-09-24 at 12 53 29 am](https://user-images.githubusercontent.com/25136650/30777078-cc02c836-a0d0-11e7-87b2-74cfada6bb0c.jpeg)

After:
![whatsapp image 2017-09-24 at 1 40 27 am](https://user-images.githubusercontent.com/25136650/30777085-e7f79d28-a0d0-11e7-8120-f9d77c2eb216.jpeg)

2017-09-25 14:57 UTC, iamareebjamal requested changes

2017-09-25 14:57 UTC, iamareebjamal commented on android/app/src/main/gen/org/fossasia/openevent/BuildConfig.java
> +package org.fossasia.openevent;
Please remove these auto generated files

2017-09-25 14:57 UTC, iamareebjamal commented on android/app/src/main/gen/org/fossasia/openevent/Manifest.java
> +public final class Manifest {
Please remove these auto generated files

2017-09-25 14:57 UTC, iamareebjamal commented on android/app/src/main/gen/org/fossasia/openevent/R.java
> +package org.fossasia.openevent;
Please remove these auto generated files

2017-09-25 14:57 UTC, iamareebjamal commented on android/app/src/main/res/layout/activity_speakers.xml
> +                    android:layout_marginRight="40dp"
Please use a value from predefined dimens

2017-09-25 14:57 UTC, iamareebjamal commented on android/build.gradle
> +        classpath 'com.android.tools.build:gradle:2.3.3'
Please don't change values not related to the particular issue, this creates problems in tracking changes over time :smile:

2017-09-25 15:52 UTC, manki11 commented
@iamareebjamal Have made the changes.

2017-09-25 16:31 UTC, iamareebjamal commented
Thanks, please also change commit message to refer to proper issue

2017-09-25 17:16 UTC, iamareebjamal commented
Please use this format so it addresses which issue it fixes. 

fix: Add margin to overlapping Speaker subtitle

2017-09-26 10:11 UTC, manki11 commented
@iamareebjamal My first PR. Sorry for the inconvenience for some reason i am unable to squash the commits into one.

2017-09-26 19:07 UTC, iamareebjamal commented
@manki11 Please follow this https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

Before this, run these commands

```
git fetch upstream development
git rebase upstream/development
```

2017-09-27 07:56 UTC, manki11 commented
@iamareebjamal did the squashing

2017-09-27 08:41 UTC, iamareebjamal commented
> Please use this format so it addresses which issue it fixes.
> 
> fix: Add margin to overlapping Speaker subtitle

Awesome, please do this as last step

2017-09-27 08:41 UTC, iamareebjamal approved these changes

2017-09-28 08:52 UTC, mariobehling commented
Thanks!

2017-09-28 08:52 UTC, merged