fix : Event bar slides down smoothly (referred to the issue-> (#1925) )
fossasia/open-event-droidgen pull request #1958
Opened 2017-10-19 10:55 UTC by dreadpool2

Changes : Event Bar animation occurs smoothly 

Screenshots for the change: 
![videotogif_2017 09 26_01 52 07](https://user-images.githubusercontent.com/28607714/31766994-27c5ce8c-b4e7-11e7-98da-d86651fb7d14.gif)

2017-10-19 18:22 UTC, dreadpool2 commented
@iamareebjamal @heysadboy  Please review!

2017-10-20 12:17 UTC, scandindian approved these changes

2017-10-20 18:27 UTC, iamareebjamal requested changes

2017-10-20 18:27 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +        AlphaAnimation a2 = new AlphaAnimation(1,0);
Please use meaningful variable names rather than `a` `b`, or `a1` `a2`

2017-10-20 18:27 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +        TranslateAnimation a  = new TranslateAnimation(0,0,-eventDescription.getHeight(),0);
Please add spaces after commas

2017-10-20 23:12 UTC, dreadpool2 commented
@iamareebjamal did the changes

2017-10-21 12:29 UTC, iamareebjamal requested changes

2017-10-21 12:29 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java
> +        TranslateAnimation event_bar_down_direction  = new TranslateAnimation(0, 0, -eventDescription.getHeight(), 0);
Please use camel case for variables

2017-10-21 14:05 UTC, dreadpool2 commented
@iamareebjamal made the changes

2017-10-21 17:47 UTC, iamareebjamal approved these changes

2017-10-22 03:02 UTC, merged