Fix #1970 appropriate text displayed when there is no result
fossasia/open-event-droidgen pull request #1972
Opened 2017-11-01 11:43 UTC by nikit19

Fixes #1970 
Changes: appropriate text is displayed when there is no result in tracks fragment,speakers fragment,location fragment and schedule fragment

Screenshots for the change: 
![ezgif com-video-to-gif 15](https://user-images.githubusercontent.com/20878145/32273250-aeddb4bc-bf27-11e7-85fb-6da887cf7018.gif)

2017-11-01 15:42 UTC, heysadboy commented
@nikit19 Looks nice. Maybe we could display text in the center and a bit bigger.

2017-11-01 16:49 UTC, nikit19 commented
@heysadboy done with the requested changes
![screenshot_20171101-221443](https://user-images.githubusercontent.com/20878145/32286163-94781a42-bf52-11e7-8c71-d951a1b9010e.png)

2017-11-03 05:46 UTC, heysadboy commented on android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
> +            if (noMicrolocationsView.getVisibility() != View.VISIBLE) {
Why are you putting it as else { if ( ) -- . Maybe you could write it as else if () { -- }

2017-11-03 05:46 UTC, heysadboy commented on android/app/src/main/java/org/fossasia/openevent/fragments/SpeakersListFragment.java
> +                noSpeakersResultView.setVisibility(View.VISIBLE);
Change nesting statement here too.

2017-11-03 05:47 UTC, scandindian requested changes
Please see the inline comments and update if else statements.

2017-11-03 07:13 UTC, nikit19 commented
@heysadboy done with the requested changes. Please review

2017-11-03 10:28 UTC, scandindian approved these changes

2017-11-03 10:50 UTC, heysadboy commented
@nikit19 Fix failing checks too please.

2017-11-03 13:40 UTC, nikit19 commented
@heysadboy all failing checks fixed

2017-11-03 18:14 UTC, heysadboy commented
@the-dagger @niranjan94 Please see.

2017-11-03 18:31 UTC, the-dagger requested changes

2017-11-03 18:31 UTC, the-dagger commented on android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
> +    private void noResult() {
Can we make this a util function with the views and values as params?

2017-11-03 20:16 UTC, nikit19 commented
@the-dagger done with the requested changes. Please review

2017-11-05 20:41 UTC, the-dagger approved these changes

2017-11-05 20:42 UTC, merged