Fix #1979 - Improve UI of call for speakers
fossasia/open-event-droidgen pull request #1985
Opened 2017-11-10 13:57 UTC by mayank8318

Fixes #1979 

Changes: Improve UI for call for speakers

Screenshots for the change: 
![image](https://user-images.githubusercontent.com/22395998/32661480-1c954278-c64d-11e7-818e-3b629058dad3.png)

2017-11-11 21:21 UTC, shreyasnbhat commented
@mayank8318 Just a suggestion.You could format the card a bit better.The text inside the card could be neatly arranged.

2017-11-12 05:20 UTC, mayank8318 commented
@shreyasnbhat What I wanted to do was to show the email - id on a new line in bold text but the entire "Announcement" string is coming from the server I guess, so I couldn't format it.
Am I right or is it hardcoded somewhere?

2017-11-25 15:17 UTC, iamareebjamal commented
Increase the padding a little bit please

2017-11-25 17:41 UTC, mayank8318 commented
Ok 👍

2017-11-26 08:03 UTC, mayank8318 commented
![image](https://user-images.githubusercontent.com/22395998/33238203-5ece239a-d2ae-11e7-961c-2cc9794bf0f4.png)

2017-11-26 18:49 UTC, iamareebjamal requested changes

2017-11-26 18:49 UTC, iamareebjamal commented on android/app/src/main/res/layout/speakers_call_dialog.xml
> +            android:padding="16dp"
Please use dimens value

2017-11-26 18:49 UTC, iamareebjamal commented on android/app/src/main/res/layout/speakers_call_dialog.xml
> +            android:textSize="20sp"
Please use a pre-existing style from compat library

2017-11-26 18:49 UTC, iamareebjamal commented on android/app/src/main/res/layout/speakers_call_dialog.xml
> +            android:padding="16dp"
Same here

2017-11-26 18:49 UTC, iamareebjamal commented on android/app/src/main/res/layout/speakers_call_dialog.xml
> +            android:padding="16dp"
Same here

2017-11-27 04:54 UTC, mayank8318 commented on android/app/src/main/res/layout/speakers_call_dialog.xml
> +            android:padding="16dp"
Ok :+1:

2017-11-27 16:39 UTC, iamareebjamal approved these changes

2017-11-27 17:05 UTC, merged