fix : Null object error fixed in track details items
fossasia/open-event-droidgen pull request #2000
Opened 2017-11-17 07:03 UTC by dreadpool2

Changes: 'To be decided' microlocations were left blank in items, so added a 'Not yet decided' line.
App doesn't crash on clicking certain items in the tracks list. (which it used to)

Screenshots for the change: 
![screenshot_20171117-123206](https://user-images.githubusercontent.com/28607714/32934864-648a2206-cb93-11e7-9e34-3fda9ae959b4.png)

2017-11-17 14:03 UTC, dreadpool2 commented
@the-dagger @iamareebjamal Please review

2017-11-25 15:02 UTC, iamareebjamal requested changes

2017-11-25 15:02 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
> +            holder.sessionLocation.setText("Not Decided Yet");
Please move this to strings.xml.
Thanks 😄

2017-11-26 10:37 UTC, dreadpool2 commented
@iamareebjamal Done the change!

2017-11-26 18:44 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
> +        } else{
Please add space after `}`

2017-11-26 18:44 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
> +
Please remove this extra line

2017-11-26 18:58 UTC, dreadpool2 commented on android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java
> +        } else{
@iamareebjamal SIr, isn't there already a space given ?

2017-11-26 19:37 UTC, dreadpool2 commented
@iamareebjamal done the changes

2017-11-27 06:48 UTC, iamareebjamal approved these changes

2017-11-27 10:17 UTC, merged