enhance: Added LocationFragment ViewModel class
fossasia/open-event-droidgen pull request #2029
Opened 2017-12-21 08:51 UTC by srv-twry

Fixes #2027 

Changes: Added ```ViewModel``` class for the ```LocationsFragment```.
Moved the database related code to the ```ViewModel```.

Screenshots for the change: NA

2017-12-21 19:25 UTC, iamareebjamal requested changes
More logic can be moved from the fragment so that most code is in the viewmodel instead of fragment. This includes state like the search query etc

2017-12-21 19:25 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/viewmodels/LocationsFragmentViewModel.java
> +public class LocationsFragmentViewModel extends ViewModel{
Please remove the template comment before committing please 😄

2017-12-21 21:26 UTC, srv-twry commented
@iamareebjamal  I have moved the search query state to the view model but that was the only thing which i was able to move from the fragment to the ViewModel.

1. RecyclerView code can't be moved.
2. Anything related to visibility of views i.e. ```HandleVisibility``` and ```SetVisibility``` can't be moved.
3. The code related to search view can't be moved (Most probably), so methods like ```onQueryTextChange``` can't be moved either.
4. The swipe to refresh layout code and methods can't be moved either.

Please point me in the right direction if i am wrong.

2017-12-21 21:51 UTC, iamareebjamal requested changes
OK. Yeah it seems like it is the only movable code :)

2017-12-21 21:51 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java
> -        realmResults.removeAllChangeListeners();
Trigger removal of listeners in the viewmodel to avoid memory leak

2017-12-21 21:51 UTC, iamareebjamal commented on android/build.gradle
> +        maven { url 'https://maven.google.com' }
This is already present as `google()` section

2017-12-22 09:16 UTC, srv-twry commented
@iamareebjamal 
1. Triggered removal of listeners in the ```onCleared``` of the view model
2. Removed redundant repository declaration.
Please review.

2017-12-22 11:45 UTC, iamareebjamal approved these changes

2017-12-22 11:46 UTC, merged