fix : speaker's image ui fix
fossasia/open-event-droidgen pull request #2065
Opened 2017-12-26 15:53 UTC by dreadpool2

Changes:The speaker image in collapsing toolbar region in activity_speakers did now covers the full frame layout.

Screenshots for the change: 
![screenshot_20171226-210151](https://user-images.githubusercontent.com/28607714/34360005-e2ea5374-ea82-11e7-8d96-fc808ea41a6d.png)

2017-12-26 16:12 UTC, srv-twry commented
@dreadpool2 Please create an issue for this PR and then link this PR to this issue :smile:

2017-12-27 09:58 UTC, mayank8318 commented
@dreadpool2 Please add the issue number in the PR comment as ->  Fix #....

2017-12-27 17:04 UTC, srv-twry commented
@dreadpool2 Please add Fixes #... in your PR comment, not in the PR title.

2017-12-28 14:07 UTC, iamareebjamal requested changes

2017-12-28 14:07 UTC, iamareebjamal commented on android/app/src/main/res/layout/activity_speakers.xml
> +                android:layout_height="@dimen/item_image_view_extra_large"
Using static height for CollapsingToolbar is alright, but doing so everywhere is not. Match Parent should be sufficient for the behaviour required here

2017-12-28 18:53 UTC, dreadpool2 commented
@iamareebjamal Done the change!

2018-01-03 09:07 UTC, dreadpool2 commented
@iamareebjamal  did the changes

2018-01-05 16:19 UTC, iamareebjamal approved these changes

2018-01-05 16:20 UTC, merged