Fix #2062 - Use default RealmLiveData wrapper.
fossasia/open-event-droidgen pull request #2069
Opened 2017-12-28 11:46 UTC by mayank8318

Fixes #2062 

Changes:
Step 1: Implement LiveRealmData for LocationsFragment.

@iamareebjamal Please review and suggest changes. I will repeat that for other view models.

2017-12-28 12:17 UTC, mayank8318 commented
App is running in my mobile but Travis says "Compilation failed" ?

2017-12-28 14:10 UTC, iamareebjamal commented
```
<===----------> 30% EXECUTING [2m 9s]> :app:compileGoogleplayDebugJavaWithJavac<===----------> 30% EXECUTING [2m 10s]<===----------> 30% EXECUTING [2m 11s]<===----------> 30% EXECUTING [2m 12s]e/travis/build/fossasia/open-event-android/android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java:87: error: cannot find symbol
                .addChangeListener((microlocations, orderedCollectionChangeSet) -> {
                ^
  symbol:   method addChangeListener((microloca[...]; } })
  location: class LiveRealmData<Microlocation>
```

2017-12-28 14:11 UTC, iamareebjamal commented
Switch to Google Play variant and compile

2017-12-29 08:38 UTC, mayank8318 commented
@iamareebjamal Please check :)

2017-12-29 09:33 UTC, iamareebjamal requested changes

2017-12-29 09:33 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java
> +    }
You can create a generic method instead

2017-12-29 09:59 UTC, mayank8318 commented
Changes : Use generic method for asLiveData( ).

2017-12-29 11:16 UTC, iamareebjamal submitted a review, later dismissed

2017-12-29 11:26 UTC, mayank8318 commented
@iamareebjamal I will repeat it for other view models which are ready.

2017-12-30 07:50 UTC, mayank8318 commented
Changes : Add wrapper for AboutViewModel.
@iamareebjamal Please review :)

2018-01-02 18:05 UTC, iamareebjamal commented
@mayank8318 Can you try this scenario:

- Go to any page with bookmarked items
- Press on an item to get detail view of that item
- Toggle the bookmark of that item
- Return to the previous screen and see if the state changed there as well

2018-01-04 14:26 UTC, mayank8318 commented
@iamareebjamal State changes in the previous screen but bookmarks are not visible in the about fragment.

2018-01-04 17:57 UTC, mayank8318 commented
Changes : Make async call for date list.
Bookmarks works when I change to another app and open Open-Event again (when it resumes focus).
@iamareebjamal Help needed! Can't find why this is happening.

2018-01-05 16:23 UTC, iamareebjamal commented
I'll look into it and get back to you :smile: Thanks for notifying

2018-01-05 18:26 UTC, iamareebjamal commented
That's because everything is asynchronous without chaining. The subscription to sessions is done after the dates are loaded, and hence before the bookmarks can be loaded, their LiveData is returned, and then the transform is done on the already subscribed data, meaning no actual event is sent to the view.

It is like - 
return instanceA;

instanceA.subscribe

After few seconds, instanceA is replaced with instanceB containing the actual bookmark events, but it's of no use because view is already subscribed to instanceA. That's why it is extremely important for shared objects to be strictly immutable. I will recommend you to temporarily make the LiveData fields final and then check out the errors to know what I am talking about. Unfortunately, we cannot make the fields final as we need to map them to RealmLiveData lazily but effectively, there should be one and only one assignment statement for a LiveData

2018-01-05 18:29 UTC, iamareebjamal commented
We could have synchronized the events easily with RxJava but it is not as easy with LiveData, so we can have a discussion and come up with a solution because there are a lot of interdependent asynchronous querying going on here. The important point here is to share a single object ALWAYS with the view and then responsibly send events in order. 

Event is loaded -> Send to view, attach date listener
Date is loaded -> Send to view, attach session listener
Sessions are loaded -> Send to view

This way it will work

2018-01-06 13:54 UTC, mayank8318 commented
Yes got it. DateList code is creating problem since I changed it to an Async call. Using the old code for `dateList` makes sense in my view since it doesn't have a change listener anyways and I tried it too ;)
@iamareebjamal Should I push my changes?

2018-01-06 18:56 UTC, iamareebjamal commented
Yes @mayank8318

2018-01-07 18:30 UTC, mayank8318 commented
Changes : Changed dateList loading back to previous version.

2018-01-07 23:24 UTC, iamareebjamal submitted a review, later dismissed

2018-01-08 10:11 UTC, mayank8318 commented
Changes : Add LiveRealmData wrapper for SpeakerListFragmentViewModel.
@iamareebjamal Please review :)

2018-01-08 19:51 UTC, iamareebjamal approved these changes

2018-01-08 19:51 UTC, merged

2018-01-08 19:52 UTC, iamareebjamal commented
Great, let's convert other ViewModels in separate PRs