Fix #2056 create viewModel for speakerDetails activity
fossasia/open-event-droidgen pull request #2077
Opened 2017-12-31 07:12 UTC by nikit19

Fixes #2056 

Changes:Created ViewModel for the SpeakerDetailsActivity

Screenshots for the change: 
![screenshot_20171231-123503](https://user-images.githubusercontent.com/20878145/34460017-c1ec81bc-ee27-11e7-9ff7-11f2193d4b45.png)

2017-12-31 07:26 UTC, dr0pdb requested changes

2017-12-31 07:26 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
> -        if(speaker != null)
This method is redundant.

2017-12-31 07:30 UTC, nikit19 commented on android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
> -        if(speaker != null)
:+1:

2017-12-31 07:45 UTC, srv-twry commented
@nikit19 While you're at it, I think you can also delete the redundant ```onSavedInstanceState``` method [here](https://github.com/nikit19/open-event-android/blob/cea1be60a1ed4af216815c872085d52f8f611ecc/android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java#L311) which does nothing except calling its super.

2018-01-10 16:22 UTC, iamareebjamal commented
@nikit19 Please change PR to use RealmDataWrapper instead

2018-01-10 18:07 UTC, nikit19 commented
@iamareebjamal updated the PR to use RealmDataWrapper.
Please review,
Thank you

2018-01-10 18:18 UTC, iamareebjamal approved these changes

2018-01-10 18:31 UTC, merged