fix: Made images zoomable
fossasia/open-event-droidgen pull request #2084
Opened 2018-01-02 04:33 UTC by srv-twry

First step for #1841 

Changes: Made the images zoomable in the LiveFeed. 

Screenshots for the change: 
![videotogif_2018 01 02_09 55 43](https://user-images.githubusercontent.com/21277837/34474374-fc6ff56c-efa3-11e7-9da6-ed3c5dd082f8.gif)

@iamareebjamal @the-dagger Please review. If it is fine then i will implement it on every image view.

2018-01-02 17:56 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +            throw new ClassCastException("Activity must implement Callbacks.");
Not good, throwing runtime exceptions based on class casting exception is like using Java like JavaScript. Java is type safe, there should be no need to convert an object in raw type and then check if it is of the correct type. I see that you did not write this implementation, but don't add more to it. There shouldn't be a `ClassCastException` if we expect the right type in the arguments.

Please also open an issue to fix the existing code and removing the exception check

2018-01-03 07:36 UTC, srv-twry commented
Changes: Removed the unnecessary check.
I have created the issue for removing it for the callback.
@iamareebjamal Please review.

2018-01-05 16:18 UTC, iamareebjamal requested changes
And you have to remove reference to the ZoomListener is onStop of fragment or activity as well or it will create a memory leak

2018-01-05 16:18 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +    public FeedAdapter(Context context, AdapterCallback adapterCallback, ZoomableImageModule zoomableImageModule, List<FeedItem> feedItems) {
Instead of adding it to constructor, make it optional and ask it as a setter

2018-01-05 16:18 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +    public FeedAdapter(Context context, AdapterCallback adapterCallback, ZoomableImageModule zoomableImageModule, List<FeedItem> feedItems) {
`ZoomableImageModule` is ambiguous. Use name like `OnImageZoomListener` and the method being `onZoom(String)`

2018-01-05 16:18 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +            });
Once you make it optional, just add a null check here as well

2018-01-06 07:38 UTC, srv-twry commented
Changes: Renamed the Listener to ```OnImageZoomListener```, Made it optional by setting it by setter, Removed reference in the onStop().

@iamareebjamal Please review.

2018-01-06 18:55 UTC, iamareebjamal requested changes
Great job. Just a few changes required :smile:

2018-01-06 18:55 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +        onImageZoomListener.onZoom(imageUri);
Suppose that the ZoomListener was not null at the time of construction but it is removed later on. Now once the image is clicked, NPE would be thrown.

2018-01-06 18:55 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +        }
No need to add null check here

2018-01-06 18:55 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +        bundle.putString(ConstantStrings.IMAGE_ZOOM_KEY,imageUri);
Add a space after comma
 
In other places as well

2018-01-06 19:15 UTC, srv-twry commented
Changes: Added null check in ```zoomImage```, removed null check in ```removeOnImageZoomListener``` and added commas.
@iamareebjamal Please review.

2018-01-06 19:27 UTC, iamareebjamal approved these changes

2018-01-06 19:28 UTC, merged