Update FeedAdapter.java
fossasia/open-event-droidgen pull request #2086
Opened 2018-01-03 13:55 UTC by divyabaid16

Fixes #[2085]

Changes: [Removed unnecessary try catch block in FeedAdapter.java]

2018-01-03 15:49 UTC, vaibhavsingh97 requested changes
Please change your PR title to `Fixes #<issue-number>: <message>`. Rest LGTM

2018-01-03 17:32 UTC, divyabaid16 commented
Thanks @vaibhavsingh97 , I have read the guidelines and made the changes accordingly.

2018-01-04 04:27 UTC, dr0pdb approved these changes

2018-01-05 15:54 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java
> +        this.mAdapterCallback = adapterCallback;
Please also change hungarian notation to simple form

2018-01-10 16:36 UTC, iamareebjamal commented
@divyabaid16 What's the status of PR?

2018-01-11 07:16 UTC, divyabaid16 commented
I will send the PR within a day.

On Wed, Jan 10, 2018 at 10:06 PM, Areeb Jamal <notifications@github.com>
wrote:

> @divyabaid16 <https://github.com/divyabaid16> What's the status of PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/open-event-android/pull/2086#issuecomment-356658719>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfOxIabv7O5CDZS4FopEeuFhbgdAJ2mUks5tJOb-gaJpZM4RRwgy>
> .
>

2018-01-11 13:41 UTC, divyabaid16 commented
@iamareebjamal I have sent a new PR #2133 . Please review it.

2018-01-11 13:42 UTC, srv-twry commented
@divyabaid16 Why a new PR ? Was there any problem ?

2018-01-11 13:54 UTC, divyabaid16 commented
@srv-twry I have added more commits in #2086 PR. Please review it. Should I close the new PR #2133  ?

2018-01-11 13:57 UTC, srv-twry commented
Yes, please close that PR. Keep one PR for an issue. Also please resolve conflicts and then squash your commits into one. 
In case you are unfamiliar with these terms, you can always google and learn :smile:

2018-01-11 14:00 UTC, srv-twry commented
Infact let's make things easy, close this one and leave that one as it is.

2018-01-11 15:11 UTC, closed without merging