removed HTML tags before saving session's info to calendar
fossasia/open-event-droidgen pull request #2097
Opened 2018-01-06 18:48 UTC by simarsingh24

Fixes #2096

2018-01-06 18:59 UTC, iamareebjamal requested changes

2018-01-06 18:59 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java
> +                intent.putExtra(CalendarContract.Events.DESCRIPTION,android.text.Html.fromHtml(session.getShortAbstract()).toString() );
Please add proper import statement and a space after comma

2018-01-06 22:17 UTC, iamareebjamal submitted a review, later dismissed

2018-01-07 11:29 UTC, simarsingh24 commented
@iamareebjamal @the-dagger I was solving another issue and accidentally pushed on the same branch. please review

2018-01-07 17:57 UTC, iamareebjamal commented
Looks good, can you please squash commits?

2018-01-07 18:12 UTC, simarsingh24 commented
@iamareebjamal Yeah, sure.

2018-01-10 16:28 UTC, iamareebjamal approved these changes

2018-01-10 16:29 UTC, merged