feat: Added Cancel button in ProgressDialog in FeedFragment
fossasia/open-event-droidgen pull request #2113
Opened 2018-01-09 15:10 UTC by srv-twry

Fixes #2076 
Changes: Added Cancel button in ProgressDialog in FeedFragment

Screenshots for the change: NA

@iamareebjamal Please review.

2018-01-09 15:16 UTC, S2606 commented
@srv-twry Can you please provide gif for this??

2018-01-09 16:38 UTC, iamareebjamal requested changes

2018-01-09 16:38 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +        feedLoaderDisposable =
No need to add an indent and a new line, just assign in the first statement

2018-01-09 16:38 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +    void disposeRxSubscriptions() {
Also check if it is already disposed

2018-01-09 16:38 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +    void disposeRxSubscriptions() {
Also make it private

2018-01-09 19:01 UTC, srv-twry commented
Changes: Added proper indentation, disposable already disposed check and made method private.
GIF: 
![videotogif_2018 01 10_00 27 29](https://user-images.githubusercontent.com/21277837/34737932-9388d1d6-f59d-11e7-86f4-fc151fa6266c.gif)

@iamareebjamal Please review.

2018-01-10 07:14 UTC, iamareebjamal approved these changes

2018-01-10 15:52 UTC, merged