memory leak fix inside track fragment
fossasia/open-event-droidgen pull request #2135
Opened 2018-01-11 16:49 UTC by simarsingh24

Fixes #2134

2018-01-11 16:53 UTC, dr0pdb requested changes

2018-01-11 16:53 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
> +        adapterDataObserver=new RecyclerView.AdapterDataObserver() {
Please add space before and after ```=```

2018-01-11 16:53 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
> +        if(tracksListAdapter!=null){
Add proper spaces here also

2018-01-11 17:02 UTC, iamareebjamal requested changes

2018-01-11 17:02 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
> +            if(adapterDataObserver!=null)adapterDataObserver=null;
No need for a null check here

2018-01-11 19:22 UTC, simarsingh24 reviewed
@iamareebjamal  if adapterDataObserver is null and is passed to unregisterAdapterDataObserver would that be erroneous? Although we havent set adapterDataObserver to null anywhere but adding an if block certainly assures we are not calling unregisterAdapterDataObserver when adapterDataObserver is null, your views?

2018-01-11 19:45 UTC, iamareebjamal commented
@simarsingh24 

```
if(adapterDataObserver!=null)adapterDataObserver=null;
```

Checking object is null just to set it null makes no sense

2018-01-11 19:50 UTC, iamareebjamal requested changes

2018-01-11 19:50 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/TracksFragment.java
> +        tracksRecyclerView.setAdapter(null);
Last 2 lines are not needed

2018-01-29 18:54 UTC, iamareebjamal approved these changes

2018-01-29 18:58 UTC, merged