fix: Save and Dispose Rx subscriptions in FeedFragment
fossasia/open-event-droidgen pull request #2142
Opened 2018-01-14 14:13 UTC by srv-twry

Fixes #2120 
Changes: Saved subscriptions in Disposables and disposed them in FeedFragment.

Screenshots for the change: NA

@iamareebjamal Please review.

2018-01-14 14:22 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +                    if (refreshFeedDisposable != null && !refreshFeedDisposable.isDisposed()) {
@iamareebjamal Should i combine them ?

2018-01-15 08:52 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +                    if (refreshFeedDisposable != null && !refreshFeedDisposable.isDisposed()) {
Yes, please combine these

2018-01-15 08:53 UTC, iamareebjamal requested changes

2018-01-15 08:53 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java
> +    private Disposable refreshFeedDisposable;
Use a final CompositeDisposable instead. This makes us remove the null checks as well

2018-01-15 09:42 UTC, srv-twry commented
Changes: Using final CompositeDisposable, Combined two ```if``` statements into one.

@iamareebjamal Please review.

2018-01-15 11:40 UTC, iamareebjamal approved these changes

2018-01-15 11:41 UTC, merged