feat: Made images zoomable in SpeakerDetailsActivity
fossasia/open-event-droidgen pull request #2164
Opened 2018-01-18 20:19 UTC by srv-twry

Fixes #2163 

Changes: Made images zoomable in SpeakerDetailsActivity

Screenshots for the change:
![videotogif_2018 01 19_01 42 00](https://user-images.githubusercontent.com/21277837/35119382-b65ba4f8-fcba-11e7-8860-c0906566eea2.gif)

@iamareebjamal Please review.

2018-01-18 20:40 UTC, iamareebjamal requested changes

2018-01-18 20:40 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
> +    }
Perhaps we can make a Utility method for this code?

2018-01-19 09:44 UTC, srv-twry commented
Changes: Added a utility class with a method for boilerplate code of showing a ZoomableImageFragmentDialog

@iamareebjamal Please review.

2018-01-19 11:23 UTC, iamareebjamal requested changes

2018-01-19 11:23 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java
> +        }
Null check can be handled inside the util method, also use TextUtils.isEmpty

2018-01-19 13:43 UTC, srv-twry commented
Changes: Added empty check in Utils method using TextUtils.isEmpty.

@iamareebjamal Please review.

2018-01-19 15:12 UTC, iamareebjamal approved these changes

2018-01-19 15:12 UTC, merged