fix: Replaced string concatenation with placeholders
fossasia/open-event-droidgen pull request #2238
Opened 2018-01-26 17:24 UTC by srv-twry

Fixes #2204 

Changes: Replaced hardcoded string concatenation with placeholders in string resources.

Screenshots for the change: NA

@iamareebjamal Please review.

2018-01-26 22:33 UTC, iamareebjamal requested changes

2018-01-26 22:33 UTC, iamareebjamal commented on android/app/src/main/res/values/strings.xml
> +    <string name="about_fragment_license_text">%s %s</string>
Just space is not a great template as it can be reused almost anywhere else. Either remove completely or rename tot general use

2018-01-27 09:59 UTC, srv-twry commented
Changes: Renamed to ```space_separated_strings```.

@iamareebjamal Please review.

2018-01-28 06:28 UTC, iamareebjamal approved these changes

2018-01-28 06:28 UTC, merged