feat: Added LiveFeed from Twitter
fossasia/open-event-droidgen pull request #2263
Opened 2018-01-27 18:16 UTC by srv-twry

Fixes #1724

Changes: Added LiveFeed from Twitter using the Loklak API.

Screenshots for the change: NA

@iamareebjamal Please review.

2018-01-28 07:26 UTC, iamareebjamal requested changes
Don't reuse the whole FeedFragment for both feeds. Follow Single Responsibility principle

2018-01-28 12:24 UTC, srv-twry commented
@iamareebjamal So should i create a new Fragment for it ?

2018-01-28 15:38 UTC, iamareebjamal commented
Yes

2018-01-29 14:04 UTC, iamareebjamal commented
Can you add a gif?

2018-01-29 14:09 UTC, srv-twry commented
![videotogif_2018 01 29_19 04 04](https://user-images.githubusercontent.com/21277837/35514393-09f74c1a-052c-11e8-9b4a-4d482a08191e.gif)

2018-01-29 14:13 UTC, srv-twry commented
Note: The API right now only returns a single entry. [API call](https://api.loklak.org/api/search.json?q=fossasia&count=20&source=twitter)

I do understand that there is a lot of common code between FeedFragment and TwitterFeedFragment and also between it's layouts.
I propose to solve this in a new issue by creating an abstract BaseFeedFragment class that will contain all the common code. Also the common code in layouts can be extracted out and used by ```include``` tags in the layout files.
I wanted to keep this PR centered at Twitter feed hence didn't change any thing in the FeedFragment.

2018-01-29 14:31 UTC, srv-twry commented
@mayank8318 @simarsingh24 Please review this PR specially for formatting errors. Since this is a relatively larger PR, I may have missed a few of them. 
Please review and let me know. :smile:  Thanks.

2018-01-29 16:43 UTC, simarsingh24 commented on android/app/src/main/java/org/fossasia/openevent/adapters/TwitterFeedAdapter.java
> +
why two new lines here?

2018-01-29 16:46 UTC, simarsingh24 commented
@srv-twry the code is actually very well formatted couldn't find any formatting changes, good job! 👍

2018-01-29 16:47 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/adapters/TwitterFeedAdapter.java
> +
Yeah, will remove it. :+1:

2018-01-29 18:31 UTC, srv-twry commented
Changes: Added TimeStamp also


![screenshot_2018-01-29-23-58-08-20](https://user-images.githubusercontent.com/21277837/35527393-9c0605be-0550-11e8-9eba-aac9fed4c9bc.png)
![screenshot_2018-01-29-23-58-00-54](https://user-images.githubusercontent.com/21277837/35527394-9d604f14-0550-11e8-8365-28d77cf85933.png)


@iamareebjamal Please review.

2018-01-29 18:47 UTC, iamareebjamal requested changes
Good job

2018-01-29 18:47 UTC, iamareebjamal commented on android/app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Please remove this

2018-01-29 18:48 UTC, srv-twry commented on android/app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Yes, i have removed it. Saw it late.

2018-01-29 18:51 UTC, iamareebjamal approved these changes

2018-01-29 18:51 UTC, merged