Fix #2220 Make composite disposible final inside the project
fossasia/open-event-droidgen pull request #2273
Opened 2018-01-29 18:25 UTC by vidu171

Fixes #2220 

Changes: Ony two instances of composite disposable were present one inside Main Activity and other inside Schedule Fragment.

2018-01-29 18:38 UTC, srv-twry commented
Please resolve conflicts.

2018-01-29 18:54 UTC, iamareebjamal commented
@vidu171 There's only one change in the PR. Also, remove null checks from final disposable if any

2018-01-29 19:27 UTC, iamareebjamal requested changes

2018-01-29 19:27 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +            disposable.dispose();
No need for isDisposed check

2018-01-29 19:28 UTC, vidu171 commented on android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java
> +            disposable.dispose();
@iamareebjamal  noted thanks

2018-01-29 19:57 UTC, vidu171 commented
@iamareebjamal  done

2018-01-29 20:03 UTC, srv-twry commented
@vidu171 Please squash your commits.

2018-02-09 13:10 UTC, vidu171 commented
I have done the requested changes and squashed rhe commits too why am i still unable to merge?

2018-02-09 13:14 UTC, srv-twry commented
@vidu171 Please resolve the conflicts. After you opened the PR, a lot of changes have already been made to the repo so you're getting merge conflicts. You will need to resolve them before you can merge.

2018-03-28 00:28 UTC, closed without merging