Fix #2287 - Move all hideKeyboard methods to a common static method.
fossasia/open-event-droidgen pull request #2308
Opened 2018-02-02 19:12 UTC by mayank8318

Fixes #2287 

Changes: Make a static method for hideKeyboard()

2018-02-02 20:53 UTC, iamareebjamal requested changes

2018-02-02 20:53 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/common/utils/Utils.java
> +    }
Should be in Views

2018-02-02 22:06 UTC, mayank8318 commented
Changes : Move method to Views.java
@iamareebjamal Please review :)

2018-02-03 00:36 UTC, iamareebjamal approved these changes

2018-02-03 00:36 UTC, merged