Fix #2284 - Add FAQs section to the app.
fossasia/open-event-droidgen pull request #2314
Opened 2018-02-04 09:28 UTC by mayank8318

Fixes #2284 

Changes:
Step 1) Create the data model.
@iamareebjamal Please review if I am on the right track here. Also, I checked the sample data for the event here - https://github.com/fossasia/open-event/tree/master/sample but I didn't find any json for the FAQs. How should I add it to the `assets` for offline use? Should I create my own sample FAQs?

2018-02-05 02:19 UTC, iamareebjamal commented
No, if not present, don't show any FAQ section

2018-02-05 03:10 UTC, mayank8318 commented
@iamareebjamal But it is documented in the API docs?

2018-02-05 03:53 UTC, iamareebjamal commented
But if only JSON is available, we can't show FAQ

2018-02-05 05:46 UTC, mayank8318 commented
Okay

2018-02-07 13:18 UTC, mayank8318 commented
Changes: Complete the FAQ functionality.

@iamareebjamal This is the response from Postman:

{
    "meta": {
        "count": 0
    },
    "links": {
        "self": "/v1/events/173/faqs"
    },
    "data": [],
    "jsonapi": {
        "version": "1.0"
    }
}

And this is the app log :
![open1](https://user-images.githubusercontent.com/22395998/35918294-463dca8e-0c37-11e8-937c-6469d0f4b2b3.png)

@iamareebjamal Please review :)

2018-02-07 17:29 UTC, iamareebjamal requested changes
Similarly from other areas

2018-02-07 17:29 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/common/events/FAQDownloadEvent.java
> +public class FAQDownloadEvent extends DownloadEvent {
Please remove author comment

2018-02-08 06:42 UTC, mayank8318 commented on android/app/src/main/java/org/fossasia/openevent/common/events/FAQDownloadEvent.java
> +public class FAQDownloadEvent extends DownloadEvent {
Okay

2018-02-08 07:29 UTC, mayank8318 commented
@iamareebjamal I made a new event id **678** and added a faq using the api. I checked with postman and I am getting the results on querying. Also I checked it by changing the api link in the config file and I am getting correct results :
![image](https://user-images.githubusercontent.com/22395998/35960333-4c448a2e-0ccf-11e8-8ed4-5d0d59d9cdbf.png)

But it is not being saved properly in realm because it returns empty results. Am I doing something wrong here?

2018-02-08 15:45 UTC, mayank8318 commented
Screenshots for the added FAQs :
![image](https://user-images.githubusercontent.com/22395998/35982202-3675e7f6-0d15-11e8-8e77-08897a9065f3.png)

2018-02-08 21:32 UTC, iamareebjamal commented
Improve UI a little bit. Use cards, don't use colors too much. And make it so the cards are collapsed by default and expand when clicked. Please add a screenshot of what happens where there is no FAQ

2018-02-09 10:51 UTC, mayank8318 commented
Changes :
Made the cards collapsible.
![27420260_1967770233251781_8946862106762805248_n](https://user-images.githubusercontent.com/22395998/36024092-a2626526-0db4-11e8-95a7-26c53fcfd5f9.gif)

- FAQs need the user to be logged in. So I am opening login screen if the user is not logged in.
-  If the user presses back, appropriate message is shown
![image](https://user-images.githubusercontent.com/22395998/36024216-169a0aac-0db5-11e8-862f-cad23253e208.png)

Empty FAQ screen :
![image](https://user-images.githubusercontent.com/22395998/36024231-21fc8b72-0db5-11e8-9ac2-d494a18c90d8.png)

@iamareebjamal Please review :)

2018-02-09 11:11 UTC, iamareebjamal commented
Good job. Just change the radius of cards to be 2dp instead

2018-02-09 11:18 UTC, mayank8318 commented
@iamareebjamal Ok will do in an hour :)

2018-02-09 13:57 UTC, mayank8318 commented
@iamareebjamal made the changes.

2018-02-09 21:03 UTC, iamareebjamal approved these changes

2018-02-09 21:04 UTC, merged