Fix #2330 Added cancel option in filter dialog box.
fossasia/open-event-droidgen pull request #2335
Opened 2018-02-14 12:31 UTC by raj10071997

Fixes #2330

Changes: Added the cancel option in the dialog box. Also removed the bug when the user presses back. When the user pressed back all the selected options were removed from the track but still the filter bar was showing the selected filtering options. Now on pressing back only the dialog box disappears.

2018-02-17 18:15 UTC, srv-twry commented
@raj10071997 Screenshot please.

2018-02-21 17:21 UTC, raj10071997 commented
@srv-twry Added the screenshot of the change and also updated the issue. Sorry for the delay.

2018-02-21 22:21 UTC, dr0pdb requested changes

2018-02-21 22:21 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/core/schedule/ScheduleFragment.java
> +                .setNegativeButton("Cancel",((dialogInterface, i) -> {
Add proper spaces.

2018-02-28 14:05 UTC, raj10071997 commented
@iamareebjamal  Please review this PR.

2018-03-04 18:23 UTC, raj10071997 commented
@iamareebjamal Please merge this PR if no changes are required in it.

2018-03-04 19:27 UTC, iamareebjamal approved these changes

2018-03-04 19:27 UTC, merged