feat: Add Session type in SessionTrackActivity (#2336)
fossasia/open-event-droidgen pull request #2337
Opened 2018-02-14 18:39 UTC by AkshayCHD

Fixes #2336 

Changes: Now the session type information is also displayed with other information about the event.

Screenshots for the change: 
![screenshot_1518633458](https://user-images.githubusercontent.com/25455546/36221520-50ec7072-11e4-11e8-95f1-142d397bc80e.png)
![screenshot_1518633466](https://user-images.githubusercontent.com/25455546/36221521-516f819c-11e4-11e8-8791-d75fcbfad1b1.png)

2018-02-14 19:47 UTC, AkshayCHD commented
@iamareebjamal please review

2018-02-15 01:01 UTC, iamareebjamal requested changes
1. Several formatting issues
2. Please don't use same UI shown for track, this will confuse the user, use subtitle instead

2018-02-15 13:08 UTC, AkshayCHD commented
@iamareebjamal what do you mean by use subtitle instead, should i display the information in subtitle textview,
can using a separate drawable before the Session Type textview serve as a solution

2018-02-15 22:36 UTC, iamareebjamal commented
`should i display the information in subtitle textview`
Yes

`can using a separate drawable before the Session Type textview serve as a solution`
Same as the current solution, not recommended. How if user gonna know what is track and type, what is clickable and what is not

2018-02-16 11:30 UTC, AkshayCHD commented
@iamareebjamal please review

2018-02-17 02:34 UTC, iamareebjamal commented
Please post screenshots for any UI changes

2018-02-17 06:49 UTC, AkshayCHD commented
@iamareebjamal screenshots have been updated

2018-02-17 10:05 UTC, iamareebjamal commented
Don't write Type: Talk

Add a subtitle in card header

2018-02-17 14:40 UTC, AkshayCHD commented
@iamareebjamal  there already is a session subtitle in the carview and a field for it, and already a field for it.
I have removed Type: from UI please review

2018-02-17 18:11 UTC, iamareebjamal commented
Screenshots are not updated

2018-02-17 21:15 UTC, AkshayCHD commented
@iamareebjamal screenshots updated

2018-02-18 05:57 UTC, iamareebjamal requested changes
Why can't session type be shown as a card header subtitle?

2018-02-20 18:27 UTC, AkshayCHD commented
@iamareebjamal i found no subtitle header for card view

2018-02-21 02:35 UTC, iamareebjamal commented
Because you have to add it. It is not present already

2018-02-21 18:07 UTC, AkshayCHD commented
@iamareebjamal please review, screenshot updated

2018-02-24 15:01 UTC, iamareebjamal commented
The subtitle should be in card header

2018-02-24 19:09 UTC, AkshayCHD commented
@iamareebjamal please review, screenshot updated

2018-02-24 23:46 UTC, iamareebjamal commented
The subtitle should be in new line rather than in the same line aligning to the right

2018-02-25 12:48 UTC, AkshayCHD commented
@iamareebjamal please review

2018-02-25 14:35 UTC, iamareebjamal commented
The alignment of subheader with title is off

2018-02-25 19:06 UTC, AkshayCHD commented
@iamareebjamal please review now, screenshots updated

2018-02-25 20:38 UTC, iamareebjamal requested changes

2018-02-25 20:38 UTC, iamareebjamal commented on android/app/src/main/res/layout/tracksactvity_item.xml
> +                    tools:text="Type" />
Why is it large? Also the padding around the item is huge. Please make it look standard yourself first

2018-02-26 15:02 UTC, AkshayCHD commented
@iamareebjamal please review

2018-02-26 15:04 UTC, iamareebjamal approved these changes

2018-02-26 15:38 UTC, merged