Fixes #2260 fixedProfileCrash added permission
fossasia/open-event-droidgen pull request #2345
Opened 2018-02-16 13:38 UTC by jindalAnuj

Fixes #2260 . app crash when pickingUp image from gallery e.g. #2260

Changes: [Permission added for picking image
added

and some code for checking android version in editprofileActivity

2018-02-16 15:40 UTC, jindalAnuj commented
@iamareebjamal please review this PR

2018-02-16 16:53 UTC, iamareebjamal requested changes

2018-02-16 16:53 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java
> +
Several syntax and style issues. Please resolve

2018-02-17 18:13 UTC, dr0pdb requested changes
Fix the formatting errors also.

2018-02-17 18:13 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java
> +            else showFileChooser();
Don't we want to show the File chooser after requesting for permissions ?

2018-02-17 18:13 UTC, srv-twry commented on android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java
> +    private void androidVersionCheck()
Rename it to ```checkAndroidVersion```

2018-02-25 20:40 UTC, iamareebjamal commented
@jindalAnuj Status?

2018-03-28 00:26 UTC, closed without merging