Enhanced the Login and Signup UI
fossasia/open-event-droidgen pull request #2375
Opened 2018-03-13 19:14 UTC by akhil117

Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

2018-04-11 13:59 UTC, Hiteshgautam01 reviewed
Add all the values to dimens.xml

2018-04-11 13:59 UTC, Hiteshgautam01 approved these changes

2018-04-11 14:07 UTC, Hiteshgautam01 commented on android/app/src/main/res/layout/content_login.xml
> +        card_view:cardCornerRadius="12dp"
Decrease the the value of the corner radius

2018-04-11 14:07 UTC, Hiteshgautam01 commented on android/app/src/main/res/layout/activity_login.xml
> +
Why are you adding unnecessary lines?

2018-05-27 18:18 UTC, bhaveshAn approved these changes

2018-05-31 19:10 UTC, nikit19 requested changes
Please remove these files. They are not needed

2018-05-31 19:10 UTC, nikit19 commented on android/app/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
this

2018-05-31 19:10 UTC, nikit19 commented on android/app/gradlew
> +exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
this

2018-05-31 19:10 UTC, nikit19 commented on android/app/gradlew.bat
> +:omega
this

2018-05-31 19:10 UTC, nikit19 commented on android/app/local.properties
> +sdk.dir=/home/akhilbatchu/Android/Sdk
this

2018-05-31 19:15 UTC, iamareebjamal commented
IMO this is not needed

2018-05-31 19:15 UTC, closed without merging