made fields final
fossasia/open-event-droidgen pull request #2438
Opened 2018-05-11 08:41 UTC by simarsingh24

Fixes #2437

2018-05-11 08:49 UTC, iamareebjamal requested changes
Put final fields on top and add a line feed between them

2018-05-11 08:49 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/discount/DiscountFragmentViewModel.java
> +    private final CompositeDisposable compositeDisposable;
Pull them together on top

2018-05-11 08:50 UTC, simarsingh24 commented on android/app/src/main/java/org/fossasia/openevent/core/discount/DiscountFragmentViewModel.java
> +    private final CompositeDisposable compositeDisposable;
okay

2018-05-11 10:06 UTC, iamareebjamal requested changes
Separate final and non-final fields by a line feed

2018-05-11 10:06 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/sponsor/SponsorsFragmentViewModel.java
> +
extra

2018-05-12 06:08 UTC, nikit19 approved these changes

2018-05-12 07:57 UTC, iamareebjamal requested changes
Please check previous request for changes

2018-05-14 11:29 UTC, iamareebjamal commented
@simarsingh24 Please resolve the conflicts

2018-05-14 18:00 UTC, simarsingh24 commented
resolve conflicts

2018-05-14 18:39 UTC, iamareebjamal approved these changes

2018-05-14 18:40 UTC, merged