added click listeners to elements of card view
fossasia/open-event-droidgen pull request #2473
Opened 2018-05-17 08:15 UTC by simarsingh24

Fixes #2472 

Changes: added click listeners to the `Speaker Linear Layout` and `Location Linear Layout`

2018-05-17 09:08 UTC, iamareebjamal commented
Use selectable item background

2018-05-21 10:12 UTC, simarsingh24 commented
@iamareebjamal  please review

2018-05-27 03:13 UTC, SIMRAN1 reviewed
@simarsingh24 first rebase your branch with development using command git pull --rebase upstream development !

2018-05-27 04:18 UTC, simarsingh24 commented
@SIMRAN1 I am not sure it's needed, its mergeable and there are no conflicts!

2018-05-27 04:24 UTC, SIMRAN1 commented
Actually by seeing this *This branch is out-of-date with the base branch* I suggested you the rebase with development branch!!

2018-05-31 19:05 UTC, simarsingh24 commented
@iamareebjamal does it need any changes?

2018-05-31 19:12 UTC, iamareebjamal requested changes

2018-05-31 19:12 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/location/LocationActivity.java
> +    private void setUIColor (int color ){
Add line feed above

2018-05-31 19:12 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/location/LocationActivity.java
> +    private void setUIColor (int color ){
Space after color

2018-05-31 19:12 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java
> +                    if(swatch != null) {
Soace after if

2018-05-31 19:12 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java
> +
Extra change

2018-05-31 19:17 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/location/LocationActivity.java
> +    private void setUIColor (int color){
Space after )

Please adhere to Java Style guidelines

2018-05-31 19:18 UTC, iamareebjamal commented on android/app/src/main/java/org/fossasia/openevent/core/location/LocationActivity.java
> +    private void setUIColor (int color){
Space after )

2018-05-31 19:21 UTC, simarsingh24 commented
resolved

2018-05-31 19:40 UTC, iamareebjamal approved these changes

2018-05-31 19:40 UTC, nikit19 approved these changes

2018-05-31 20:36 UTC, merged